### ISSUE TITLE
Commits history from non-top authors is missing in "Commits per Author" graph

### ISSUE THREAD

**Issue by vifactor** [vifactor/repostat#119]
Both v1.3 and v2.x. Same for "Cumulated Added Lines of Code per Author"

**Comment by pulkomandy** [comment]
There is code to generate it in 1.3 but it is enabled only if there are less than max_authors. This makes some sense for commits per author drawn as a line, but not as a stacked graph or in a streamchart.

I did not implement it in the nvd3 branch yet. I'll let you decide how to best do it if you're working on the backend.

**Comment by vifactor** [comment]
For streamchart it is definitely does not make sense, but apparently there is a bug (even 2): `len(authors_to_plot) > self.configuration['max_authors']:` always false... and even if it was true, gnuplot would not plot it because in corresponding "*.plot" file there is another bug :)

Anyway, for backend it is not a big deal and for what you do it is even not needed. But for v1.3 in stacked graph I find it useful:
![commits_by_author](https://user-images.githubusercontent.com/6075578/79016677-e1512800-7b6f-11ea-9233-0d16c5b1a865.png)
