### ISSUE TITLE
Use a better/smarter integration period for author stats

### ISSUE THREAD

**Issue by pulkomandy** [vifactor/repostat#124]
Currently author stats are grouped by week. This is fine for young projects, but for older ones it doesn't work so well. In particular, the streamgraph does not look great, it tends to be a lot of short pulses which is hard to interpret anything from.

Using a month or even a quarter as the integration period would yield better results.

I don't know if the same is true for the two other graphs in author stats (lines and commits count), maybe a quarter would be too coarse there when it is fine for the streamgraph. So we may need a different integration period for the streamgraph.

**Comment by vifactor** [comment]
So far I am going to add a single configuration option in config file, so that a user could adjust a global sampling. Can be reopen if individual graph adjustments are needed.
