### ISSUE TITLE
Identifying lost knowledge in a source code 

### ISSUE THREAD

**Issue by vifactor** [vifactor/repostat#138]
https://www.feststelltaste.de/identifying-lost-knowledge-in-the-linux-kernel-source-code/
* [x] For which source file can we ask most of the authors?
* [x] For how many source files is only one author coding?
* [x] Ratio of known code to unknown code (= code older than "six months")
* [x] Top knowledge carriers (developers did the most changes in last "six month")
* [x] Do not plot graphs or render tables from this PR if `--contribution` option is not provided

**Comment by mestaritonttu** [comment]
>     * [ ]  Ratio of known code to unknown code (= code older than six months)

What about having more detailed info about this, like "which files/directories contain the oldest code relative to LOC?" Not sure what would be the best way to present the age distribution data. I think this would be useful for bigger projects with a long history.

**Comment by vifactor** [comment]
Sure, the list of metrics to display is not complete in this issue and there is indeed a plan to add the metrics you suggest.
I have the same concern as you have, though: what would be the best way to present the data.

**Comment by mestaritonttu** [comment]
Great! I guess some designer or data visualiser might be able to help. All I can think of for now is to perhaps consult the friendly [Open Source Design](https://discourse.opensourcedesign.net/) community.
