### ISSUE TITLE
Decouple max_authors settings for summary table and graphs

### ISSUE THREAD

**Issue by vifactor** [vifactor/repostat#146]
Normally table may contains more rows, while it is sane to limit number of authors in graphs, e.g. because of limited number of colors

**Comment by pulkomandy** [comment]
Should it? For large projects this would make a very long table (hundreds of contributors with one or two commits). In Haiku I would like to use about 20 authors for the table, and 10 for the graphs, I think.

**Comment by vifactor** [comment]
I had this idea of a table with metrics over all authors because you might be a not-top contributor, but still check what was your impact. At least config for the number of contributors in table must be decoupled from the one in graphs
