### ISSUE TITLE
brew install instructions no longer work

### ISSUE THREAD

**Issue by teague-lasser** [vifactor/repostat#150]
### Problem
Running `brew install libgit2` on `MacOS Catalina` is no longer sufficient because in installs a higher version of libgit2:
```
% brew install libgit2
Warning: libgit2 1.0.0 is already installed and up-to-date
To reinstall 1.0.0, run `brew reinstall libgit2`
```

which results in `pip3 install git+https://github.com/vifactor/repostat` failing because it expects an older version
```
    #error You need a compatible libgit2 version (v0.28.x)
```

### Fix
Upgrading the requirement to pygit2 1.2.0 and installing it from github fixed this for me

**Comment by vifactor** [comment]
Thanks for reporting! I'll update requirements

**Comment by vifactor** [comment]
I have relaxed restrictions on the pygit2 version requirement and slightly updated the README. Although, Homebrew looks quite simple it may cause problems even more complicated than you experienced. So the recommended way to install pygit2 is to build it with libgit2 from source (that is what CI does)
