### ISSUE TITLE
Incorrect value for "commits count" in author of the year table

### ISSUE THREAD

**Issue by pulkomandy** [vifactor/repostat#188]
http://pulkomandy.tk/stats_hp/authors.html generated from github.com/haikuports/haikuports

The "Author of the year" for 2017 is listed with only 3 commits in that year, which I'm fairly sure is incorrect, it should be 1029 according to the streamgraph.

**Comment by vifactor** [comment]
I tried to investigate a bit and found that 'korli' must be Jerome Duval, but name 'korli' appears only in years 2011-2012, while in your report I see it everywhere. 
Did you use git mailmap file?

**Comment by pulkomandy** [comment]
Ah, yes. On such a long project people change e-mails and git configuration over time so there has to be a mailmap.

Mailmap is here if you need it: http://pulkomandy.tk/drop/.mailmap

**Comment by vifactor** [comment]
Anyway, indeed there is a bug. Will try to fix soon.

**Comment by vifactor** [comment]
Extremelly misterious bug related to my understanding on how pandas works...

Apparently, I should have used `series.iloc[0]` instead of `series[0]`.
What is misterious is that for all years in `haikuports` both give the same result except for 2017...
