### ISSUE TITLE
Graphs is missing

### ISSUE THREAD

**Issue by gandadil** [vifactor/repostat#199]
I have installed  repostat with "pip3 install repostat-app" inside a virtualenv. Just run without any errors but the directory have just html and js files. There is no graphics or CSS, like you can see below. The repostat version is 2.2.0

![image](https://user-images.githubusercontent.com/48427120/99722186-1111c800-2a8f-11eb-8b13-8d92a6078672.png)
![image](https://user-images.githubusercontent.com/48427120/99722391-5e8e3500-2a8f-11eb-9f01-77bd17f46b2d.png)

**Comment by pulkomandy** [comment]
Is this with or without the --copy-assets option? Can you check the path to the assets (css and js files) in the generated html? By default without --copy-assets it should refer to the data where pip installed it. With --copy-assets the css and js files are instead copied next to the html files, so it's easier to share the resulting page (put it on a webserver for example).

**Comment by gandadil** [comment]
I miss this parameter. Just put now and resolved the problem. Thank you!
