### ISSUE TITLE
Pull requests and reviews

### ISSUE THREAD

**Issue by chahank** [vifactor/repostat#204]
Dear developers,

Would it possible to obtain the statistics for the pull requests and the performed reviews per author?

**Comment by pulkomandy** [comment]
"Pull requests" are not a thing in Git, they are specific to Github (or other similar tools). The only thing we can get by looking at the git repository is the merge commits. We already do two things with these:
- Show the number of merge commits from each author in the "top authors" table
- Show "review duration" at the bottom of the activity page, indicating how long a commit remained in review before being merged.

**Comment by chahank** [comment]
Oh yes, sorry and thanks for the fast reply. I was to quick to ask.
