### ISSUE TITLE
CSV Output feature

### ISSUE THREAD

**Issue by BereGabor** [vifactor/repostat#32]
Implement new CSV Output feature. CSV files can used to load data any data analyse or visualizer system.

new cli option: **output**  valid values: **html**, **csv**
default is 'html'

with html value generate the html riport as the current main feature.
with csv value generate some csv output: authors, commits details... and so on.

Project name and repo name have to be in csv files.

**Comment by BereGabor** [comment]
I have forked the repo and implement this feature :)

**Comment by vifactor** [comment]
great! You are welcome to send a pull request, perhaps, this will motivate me to work on the project :)
