### ISSUE TITLE
Replace embedded png graphs with interactive html graphs

### ISSUE THREAD

**Issue by vifactor** [vifactor/repostat#5]
http://gnuplot.sourceforge.net/demo_canvas_5.2/

**Comment by vifactor** [comment]
It looks like it is not worth to migrate to gnuplot's canvas terminal. The functionality out of the box is limited, e.g. for a plot with an inset only one pair of axis becomes interactive. For multiple plots on a page, a heavy java script coding is required.

Also it is not clear why to use jsdir option if required css and js files come with gnuplot's distribution, however, automatic detection of a path to these scripts is not provided. Workaround needed.

**Comment by vifactor** [comment]
one of the alternatives is [pygal](http://pygal.org/en/stable/):
- very simple
- nice documentation
- generates embedded interactive plots

But:
- does not have zooming and panning
- does not allow inset plots

**Comment by vifactor** [comment]
Among other alternatives, [Bokeh](https://bokeh.pydata.org) and [altair](https://altair-viz.github.io/) are in active development. I would prefer Bokeh because of simple and clear procedure to embed its plots into html. Unfortunately, the later package does provide [streamgraph](https://datavizcatalogue.com/methods/stream_graph.html) plot out of the box, which looks natural for diplaying authors' contribution. 
Should try to implement the functionalily using [the recipe](https://github.com/laserson/pytools/blob/master/streamgraph.py).

**Comment by pulkomandy** [comment]
I found echarts which looks nice and the syntax seems not too hard: https://echarts.apache.org/examples/en/editor.html?c=themeRiver-basic

I don't know how easy it is to integrate however

**Comment by vifactor** [comment]
Same here, not sure I will find time to work on it.

**Comment by pulkomandy** [comment]
Found yet another possible one: http://nvd3.org/index.html

Seems easy to integrate (it's all javascript), data input is just json which we could easily generate, and it has steam charts and a 'viewfinder' in its demos. Did not see an example of an inset plot, but I think we can do away with that if it's the only missing thing.

**Comment by vifactor** [comment]
thanks to @pulkomandy , this long-lasting issue is now resolved! Nvd3 is the js-library used to render graphs for repostat.
