### ISSUE TITLE
How do we use repostat on windows?

### ISSUE THREAD

**Issue by GeekSpring** [vifactor/repostat#57]
How do we use repostat on windows? thanks

**Comment by vifactor** [comment]
Since I forked the repository, I haven't tried to run it on Windows. Will work on that if find time.

**Comment by vifactor** [comment]
@BereGabor could you, please, take a look? If I remember correctly, you work with Windows

**Comment by BereGabor** [comment]
You can use repostat as a simple cli command practically from cmd.

Here is an example call: 
`python gitstats.py --output_format=html c:\git\repostat  c:\statistic_output`

or you can get the usage info
`python gitstats.py --help`

python is not in windows PATH environment variable. Here is a [guide](https://geek-university.com/python/add-python-to-the-windows-path/) how you can do this. 

Prereqs:
python 3+ install required. [Python 3.7](https://www.python.org/ftp/python/3.7.3/python-3.7.3.exe)

repostat install:
You can find the repostat script install instruction in README.MD on [repostat git repo](https://github.com/vifactor/repostat)

**Comment by GeekSpring** [comment]
@BereGabor  thanks,we  try  it !

**Comment by vifactor** [comment]
@GeekSpring,  would be grateful for having your feedback here whether you succeed or found any issues running repostat on Windows.
