### ISSUE TITLE
Migrate command option parsing from getopt to argparse

### ISSUE THREAD

**Issue by vifactor** [vifactor/repostat#7]

**Comment by BereGabor** [comment]
I implement this issue

**Comment by vifactor** [comment]
Great! May I ask you then when you do that, please, separate the command option parsing and analysis launching into different files, i.e. gitstats split into e.g. repostat.py (main file with argparse, check dependencies, usage, etc.) and git_repo_analysis.py (which would contain for now html report creator and data collector).

**Comment by BereGabor** [comment]
Ok. I could move data collector and HTMLGenerator classes in separate files too.

**Comment by BereGabor** [comment]
I would like to submit the whole solution in more PR. The first should be the refact to avoid difficult merges.  ( as i currently do :) )

**Comment by BereGabor** [comment]
Subtask under this issues as i see. I'll submit PR per subtask if it's OK:

- [ ] **Refact code**: in progress PR submited
- [ ] **PEP8 style, pycharm re format, and warning fixes**: under dev. (optional)
- [ ] **migrate command**: todo

We could do this?

**Comment by vifactor** [comment]
I am absolutely fine for all three points in your plan
