### ISSUE TITLE
Non-local browse is broken

### ISSUE THREAD

**Issue by sjoubert** [vifactor/repostat#74]
With #65 two use cases seem broken now:
1. The generated report can't be served by an HTML server anymore since the repostat installation dir is likely not in correct folders allowed by the server. For example, aggregating the report as Jenkins artifacts now only serves the html. Jenkins refuses to provided the css and js from the repostat installation dir.
2. The generated report is not relocatable anymore. For example, generating reports on a build machine then aggregating multiple reports on a single host dedicated to stats requires repostat to be installed on the end machine (and in the same place as the build hosts)

I don't know what were the reason for removing the assets from the report (reducing space usage I guess, but the assets size is not that big), but having standalone relocatable reports should be a valid use case in my opinion.

**Comment by sjoubert** [comment]
IMO having a standalone report folder should be the default as I think people may be confused in these broken cases. I'd prefer a `--no-copy--assets` if needed but `--copy--assets` would work too.

**Comment by vifactor** [comment]
@sjoubert , I have provided the option to make report relocatable
