### ISSUE TITLE
Enable git mailmap functionality

### ISSUE THREAD

**Issue by jonespm** [vifactor/repostat#77]
In our repository, we have some author entries where the email address was not specified correctly

`Author: RAUL SANCHEZ VEGAS <RAUL SANCHEZ VEGAS>`

This is throwing a value error and aborting. I think it would be better if either
1) A fake domain was returned for these entries that would fail (like maybe just localhost, or configurable?)
2) A configuration to map these to valid names was provided

```
 [0.01462] >> gnuplot --version
Git path: /home/jonespm/docker-sakai-script/sakai
Collecting data...
Fetching authors info...
Finished in 268149.16 ms
Fetching tags info...
Finished in 514.82 ms
Fetching domains info...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/analysis/gitstatistics.py", line 303, in fetch_domains_info
    _, domain = split_email_address(commit.author.email)
  File "/usr/lib/python3/dist-packages/analysis/gitstatistics.py", line 32, in split_email_address
    raise ValueError('Not an email passed: %s' % email_address)
ValueError: Not an email passed: RAUL SANCHEZ VEGAS

```

**Comment by vifactor** [comment]
I'll fix exception ASAP. Mapping will also be done through [git mailmap](https://git-scm.com/docs/git-check-mailmap).

Btw, how do you install repostat? ppa or pip?

**Comment by vifactor** [comment]
Exception handling is fixed in master-branch. Unfortunately, the git mailmap functionality was added in pygit2 v.0.28, so I need to update my libgit2 to implement and check new functionality. Will take some time.

**Comment by jonespm** [comment]
I installed from pip. When testing I cloned and installed from my local repo. 

I actually was going to suggest a feature like mailmap because we use this and it didn't seem to work for me. We have a .mailmap available but it didn't seem to do anything. That would work as well to work around this.  The diff I did for this to get around it was just this below, but I'd for sure use the mailmap support.

Thanks again!

```
diff --git a/analysis/gitstatistics.py b/analysis/gitstatistics.py
index de1a2c3..00bc3c3 100644
--- a/analysis/gitstatistics.py
+++ b/analysis/gitstatistics.py
@@ -29,7 +29,7 @@ class FixedOffset(tzinfo):
 def split_email_address(email_address):
     parts = email_address.split('@')
     if len(parts) != 2:
-        raise ValueError('Not an email passed: %s' % email_address)
+        return parts[0], "localhost"
     return parts[0], parts[1]
```
