### ISSUE TITLE
Commit by month graph overlay hides commits by year

### ISSUE THREAD

**Issue by pulkomandy** [vifactor/repostat#88]
As seen here:
http://pulkomandy.tk/repostat-test/activity.html

Compare with graph from old gitstats on the same repo:
http://pulkomandy.tk/stats_hp/activity.html

**Comment by vifactor** [comment]
I see, I'll think how to make it better. Thanks for reporting.

**Comment by vifactor** [comment]
@pulkomandy , I have pushed possible solition. Would appreciate your feedback. If you have a better proposition, I am glad to implement it or merge your PR. Thanks for reporting

**Comment by pulkomandy** [comment]
Yes, looks fine to me. Thanks!
