### ISSUE TITLE
Rename general.html to index.html

### ISSUE THREAD

**Issue by pulkomandy** [vifactor/repostat#90]
It would make it the landing page if the generated files are put on a web server. In the current situation, one gets a list of files and must open one of the html files manually to get to the repostat pages.

(not very important, I'll workaround this with a symlink I guess).

**Comment by vifactor** [comment]
There is now symlynk to `general.html` called `index.html` after report generation

**Comment by vifactor** [comment]
There is a problem to handle symlinks in Windows and actually for deployment of generated report as a static website symlink is not useful. So there will be a command line option added to create index.html page as a copy of General page.
