### ISSUE TITLE
Commits per author graph can be misleading

### ISSUE THREAD

**Issue by pulkomandy** [vifactor/repostat#92]
For example look at the graph for repostat itself:
http://pulkomandy.tk/repostat-test/commits_by_author.png

At a first glance it looks like Heikki Hokkanen is very active in the last few years, as their curve is raising steeply. But in fact they are inactive, and the curve raises only because it is pushed from below by other contributors.

While the graph in the old gitstats was more crowded, at least it allowed to see inactive contributors (horizontal flat line), and make more sense of when contributors started working on things, when their lines crossed someone else's, etc. So I prefer the old behavior here.

**Comment by vifactor** [comment]
Partially agree on this. But what would really be nice to have instead is "stream plot" which is long awaiting feature (see #14 ). 
This graph is cummulative sum of commits, so it does not give you (direct) insight about activity of a user, but rather contribution (in this particular case) percentage of commits by author at any given point of time.

Anyway, I might think to return the original "gitstats" graph back. As stream graph is something not easy to generate with gnuplot.

**Comment by pulkomandy** [comment]
The svg_graphs branch fixes this as it uses an actual streamgraph and also brings back the line chart as in gitstats.
